spring:
  application:
    name: auth-service

  data:
    mongodb:
      uri: mongodb://admin:pass@mongo:27017/authdb?authSource=admin

  jackson:
    serialization:
      indent_output: true

  security:
    jwt:
      secret-key: YourVerySecretKey
      token-duration: 1D

server:
  port: 7050

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
